WineShop/Areas/Administrator/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WineShop.Models;
using PagedList;
using System.IO;
using System.Text.RegularExpressions;
using System.Net;
using System.Web.Helpers;
using iTextSharp.text.pdf;
using iTextSharp.text;
namespace WineShop.Areas.Administrator.Controllers
{
    
    public class SanPhamController : Controller
    {
        ShopRuouDBEntities db = new ShopRuouDBEntities();
        // GET: Administrator/SanPham
        
        public ActionResult Index(string sortOrder, string currentFilter, string TimSanPham, int? page)
        {
            if(Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            ViewBag.CurrentFilter = sortOrder;
            Session["a"] = "SanPham";
            ViewBag.TenSanPhams = string.IsNullOrEmpty(sortOrder) ? "sanpham_desc" : "";
            ViewBag.SoLuocXems = sortOrder == "luocxem" ? "luocxem" : "luocxem_desc";
            ViewBag.SoLuongBans = sortOrder == "luongban_desc" ? "luongban_desc" : "luongban";

            var spList = db.SanPhams.Where(s =>  s.BiXoa.Value == 0);

            switch (sortOrder)
            {
                case "luocxem_desc":
                    spList = spList.OrderByDescending(s => s.SoLuocXem);
                    break;
                case "luocxem":
                    spList = spList.OrderBy(s => s.SoLuocXem);
                    break;
                case "luongban_desc":
                    spList = spList.OrderByDescending(s => s.SoLuongBan);
                    break;
                case "luongban":
                    spList = spList.OrderBy(s => s.SoLuongBan);
                    break;
                case "sanpham_desc":
                    spList = spList.OrderByDescending(s => s.TenSanPham);
                    break;
                default:
                    spList = spList.OrderBy(s => s.TenSanPham);
                    break;
            }

            if (TimSanPham != null)
            {
                page = 1;
            }
            else
            {
                TimSanPham = currentFilter;
            }

            ViewBag.CurrentFilter = TimSanPham;

            if (!string.IsNullOrEmpty(TimSanPham))
            {
                spList = spList.Where(s => s.TenSanPham.Contains(TimSanPham.Trim()));
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(spList.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ChiTiet(int? id)
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sp = db.SanPhams.Where(s => s.MaSanPham == id && s.BiXoa == 0).First<SanPham>();
            return View(sp);
        }

        public ActionResult ThemMoi()
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            List<LoaiSanPham> listLoaiSanPham = db.LoaiSanPhams.ToList<LoaiSanPham>();
            List<HangSanXuat> listHangSanXuat = db.HangSanXuats.ToList<HangSanXuat>();
            ViewBag.LoaiSanPhams = new SelectList(listLoaiSanPham, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.HangSanXuats = new SelectList(listHangSanXuat, "MaHangSanXuat", "TenHangSanXuat");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemMoi([Bind(Include = "MaSanPham, TenSanPham, GiaSanPham, NgayNhap, MoTa,SoLuongTon, MaLoaiSanPham, MaHangSanXuat, Hinh")] SanPham sanpham, IEnumerable<HttpPostedFileBase> upload)
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    sanpham.HinhAnhs = new List<WineShop.Models.HinhAnh>();
                    foreach (var file in upload)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            string extension = Path.GetFileNameWithoutExtension(file.FileName);
                            string timeUTC = DateTime.Now.ToFileTimeUtc().ToString();
                            string a = file.FileName.Replace(extension, timeUTC);

                            String logoPath = Path.GetFileName(a);
                            var hinh = new WineShop.Models.HinhAnh
                            {
                                TenHinh = logoPath,
                                BiXoa = false
                            };
                            file.SaveAs(Path.Combine(Server.MapPath("~/Images/"), hinh.TenHinh));
                            sanpham.HinhAnhs.Add(hinh);
                        }
                    }
                }
                sanpham.SoLuongBan = 0;
                sanpham.SoLuocXem = 0;

                sanpham.BiXoa = 0;
                db.SanPhams.Add(sanpham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<LoaiSanPham> listLoaiSanPham = db.LoaiSanPhams.ToList<LoaiSanPham>();
            List<HangSanXuat> listHangSanXuat = db.HangSanXuats.ToList<HangSanXuat>();
            ViewBag.LoaiSanPhams = new SelectList(listLoaiSanPham, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.HangSanXuats = new SelectList(listHangSanXuat, "MaHangSanXuat", "TenHangSanXuat");

            return View(sanpham);
        }

        public ActionResult Xoa(int? id)
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            SanPham sp = db.SanPhams.Single(s => s.MaSanPham == id.Value);
            int chiTietDonDatHangCount = sp.ChiTietDonDatHangs.Count;
            var hinhAnhList = sp.HinhAnhs;
            if (hinhAnhList.Count > 0)
            {
                foreach (var r in hinhAnhList)
                {
                    string hinhCu = Request.MapPath("~/Images/" + r.TenHinh);
                    if (System.IO.File.Exists(hinhCu))
                    {
                        System.IO.File.Delete(hinhCu);
                    }
                    //r.MaSanPham = null;
                    //r.BiXoa = true;
                }
                var hinhAnhDB = db.HinhAnhs;
                foreach(var r in hinhAnhList.ToList())
                {
                    var hinhTemp = hinhAnhDB.Single(h => h.Ma == r.Ma);
                    if(hinhTemp != null)
                    {
                        db.HinhAnhs.Remove(hinhTemp);
                    }
                }
            }


            if (chiTietDonDatHangCount == 0)
            {
                db.SanPhams.Remove(sp);
            }else
            {
                sp.BiXoa = 1;
            }
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult CapNhat(int? id)
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sp = db.SanPhams.Single(s => s.MaSanPham == id);

            List<LoaiSanPham> listLoaiSanPham = db.LoaiSanPhams.ToList<LoaiSanPham>();
            List<HangSanXuat> listHangSanXuat = db.HangSanXuats.ToList<HangSanXuat>();
            ViewBag.LoaiSanPhams = new SelectList(listLoaiSanPham, "MaLoaiSanPham", "TenLoaiSanPham");
            ViewBag.HangSanXuats = new SelectList(listHangSanXuat, "MaHangSanXuat", "TenHangSanXuat");

            return View(sp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhat([Bind(Include = "MaSanPham, TenSanPham, GiaSanPham, NgayNhap, SoLuongTon, MoTa, MaLoaiSanPham, MaHangSanXuat")] SanPham sanpham, IEnumerable<HttpPostedFileBase> upload, IEnumerable<String> GiaTri)
        {
            if (Session["DangNhapAdmin"] == null)
            {
                return RedirectToAction("Index", "DangNhap");
            }
            if (ModelState.IsValid)
            {
                SanPham sp = db.SanPhams.Single<SanPham>(s => s.MaSanPham == sanpham.MaSanPham );
                sp.TenSanPham = sanpham.TenSanPham;
                sp.MoTa = sanpham.MoTa;
                sp.NgayNhap = sanpham.NgayNhap;
                sp.SoLuongTon = sanpham.SoLuongTon;
                sp.GiaSanPham = sanpham.GiaSanPham;
                sp.MaLoaiSanPham = sanpham.MaLoaiSanPham;
                sp.MaHangSanXuat = sanpham.MaHangSanXuat;
                if(GiaTri != null)
                {
                    var listHinhAnh = sp.HinhAnhs;
                    foreach (var r in GiaTri)
                    {
                        int maHinh = Int16.Parse(r);
                        HinhAnh ha = listHinhAnh.Single(h => h.Ma == maHinh);

                        string hinhCu = Request.MapPath("~/Images/" + ha.TenHinh);
                        if (System.IO.File.Exists(hinhCu))
                        {
                            System.IO.File.Delete(hinhCu);
                        }
                        //ha.BiXoa = true;
                        //ha.MaSanPham = null;
                    }
                    var hinhAndList = db.HinhAnhs.ToList();
                    foreach(var r in GiaTri)

WineShop/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WineShop.Models;
using PagedList;
namespace WineShop.Controllers
{
    public class SanPhamsController : Controller
    {
        ShopRuouDBEntities db = new ShopRuouDBEntities();

        [ChildActionOnly]
        public PartialViewResult Search()
        {
            var result = db.LoaiSanPhams.ToList();
            ViewBag.LSPs = new SelectList(result, "MaLoaiSanPham", "TenLoaiSanPham");

            var result2 = db.HangSanXuats.ToList();
            ViewBag.HSXs = new SelectList(result2, "MaHangSanXuat", "TenHangSanXuat");

            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult SanPhamCungLoai(int id)
        {
            ViewBag.TieuDe = "Sản Phẩm Cùng Loại";
            SanPham sp = db.SanPhams.Single(s => s.MaSanPham == id);
            List<SanPham> lst = db.SanPhams.Where(s => s.BiXoa == 0 && s.MaLoaiSanPham == sp.MaLoaiSanPham && s.MaSanPham != id).Take(8).ToList<SanPham>();

            return PartialView( lst);
        }

        [ChildActionOnly]
        public ActionResult MenuLoai()
        {
            List<LoaiSanPham> lst = db.LoaiSanPhams.Where(s => s.BiXoa == 0).ToList<LoaiSanPham>();
            return PartialView(lst);
        }

        [ChildActionOnly]
        public ActionResult MenuHang()
        {
            List<HangSanXuat> lst = db.HangSanXuats.Where(s => s.BiXoa == 0).ToList<HangSanXuat>();
            return PartialView(lst);
        }


        public ActionResult HienThiSanPhamTheoLoai(int id, int? page)
        {
            if (Session["BiKhoa"] != null)
            {
                return RedirectToAction("LogOffs", "Account");
            }
            ViewBag.TenAction = "HienThiSanPhamTheoLoai";

            int pageNumber = (page ?? 1);
            int pageSize = 4;

            var lst = db.SanPhams.Where(s => s.BiXoa == 0 && s.MaLoaiSanPham == id).OrderBy(s=>s.MaSanPham);
            LoaiSanPham loai = db.LoaiSanPhams.Single(l => l.MaLoaiSanPham == id);
            ViewBag.TieuDe = "Danh sách sản phẩm theo Loại " + loai.TenLoaiSanPham;

            return View("DanhSachSanPham",lst.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult HienThiSanPhamTheoHang(int id, int? page)
        {
            if (Session["BiKhoa"] != null)
            {
                return RedirectToAction("LogOffs", "Account");
            }
            var lst = db.SanPhams.Where(s => s.BiXoa == 0 && s.MaHangSanXuat == id).OrderBy(s=>s.MaSanPham);
            HangSanXuat hang = db.HangSanXuats.Single(l => l.MaHangSanXuat == id);
            ViewBag.TieuDe = "Danh sách sản phẩm theo Hãng " + hang.TenHangSanXuat;
            int pageNumber = (page ?? 1);
            int pageSize = 4;
            return View("DanhSachSanPham", lst.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult HienThiChiTietSanPham(int id)
        {
            if (Session["BiKhoa"] != null)
            {
                return RedirectToAction("LogOffs", "Account");
            }
            //List<SanPham> lst = db.SanPhams.Where(s => s.BiXoa == 0 && s.MaSanPham == id).ToList<SanPham>();
            SanPham hang = db.SanPhams.Single(s=> s.BiXoa == 0 && s.MaSanPham == id);
            hang.SoLuocXem = hang.SoLuocXem + 1;
            db.SaveChanges();
            return View("ChiTiets", hang);
        }

        public ActionResult TimKiemSP(int? page)
        {
            if (Session["BiKhoa"] != null)
            {
                return RedirectToAction("LogOffs", "Account");
            }
            ViewBag.TieuDe = "Sản Phẩm Tìm Được";
            int pageNumber = (page ?? 1);
            int pageSize = 4;
            var sp = Session["DSTimKiemSanPham"] as IOrderedQueryable<SanPham>;
            if(sp == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("DanhSachSanPham", sp.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult TimKiemSP(string txtTimkiem, int? MaLoaiSanPham, int? MaHangSanXuat, int? txtGia1, int? txtGia2, int? page)
        {
            if (Session["BiKhoa"] != null)
            {
                return RedirectToAction("LogOffs", "Account");
            }
            ViewBag.TieuDe = "Sản Phẩm Tìm Được";
            var sp = db.SanPhams.Where(s => s.BiXoa == 0).OrderBy(s => s.MaSanPham);
            int soLuong = sp.Count();
            int pageNumber = (page ?? 1);
            int pageSize = 4;

           
            if (txtTimkiem != null)
            {
                sp = sp.Where(s => s.TenSanPham.Contains(txtTimkiem)).OrderBy(s => s.MaSanPham);
            }
            if (MaLoaiSanPham != null)
            {
                sp = sp.Where(s => s.MaLoaiSanPham == MaLoaiSanPham.Value).OrderBy(s => s.MaSanPham);
            }
            if (MaHangSanXuat != null)
            {
                sp = sp.Where(s => s.MaHangSanXuat == MaHangSanXuat.Value).OrderBy(s => s.MaSanPham);
            }

            if (txtGia1 != null && txtGia1.Value >= 0)
            {
                sp = sp.Where(s => s.GiaSanPham >= txtGia1.Value).OrderBy(s => s.MaSanPham);
            }
            if (txtGia2 != null && txtGia2.Value >= 0)
            {
                sp = sp.Where(s => s.GiaSanPham <= txtGia2.Value).OrderBy(s => s.MaSanPham);
            }
            if(sp.Count() == soLuong)
            {                
                return RedirectToAction("Index","Home");
            }
            Session["DSTimKiemSanPham"] = sp;
            return View("DanhSachSanPham", sp.ToPagedList(pageNumber, pageSize));
        }

    }
}

WineShop/Views/SanPhams/ChiTiets.cshtml
@model  WineShop.Models.SanPham

<div class="columns-container">
    <div class="container" id="columns">
        <!-- row -->
        <div class="row">
            @{ var item = Model;}
            <!-- Center colunm-->
            <div class="center_column col-xs-12 col-sm-12" id="center_column">
                <!-- Product -->
                <div id="product">
                    <div class="primary-box row">
                        <div class="pb-left-column col-xs-12 col-sm-5">
                            <!-- product-imge-->
                            <div class="product-image">
                                <div class="product-full">
                                    @foreach (var h in item.HinhAnhs)
                                    {
                                        <img id="product-zoom" src="~/Images/@h.TenHinh" width="500" height="400"/>
                                        break;
                                    }
                                </div>
                                <div class="product-img-thumb" id="gallery_01">
                                    <ul class="owl-carousel" data-items="3" data-nav="true" data-dots="false" data-margin="21" data-loop="false"></ul>
                                </div>
                            </div>
                            <div class="product-img-thumb" id="gallery_01">

                                <ul class="owl-carousel" data-items="3" data-nav="true" data-dots="false" data-margin="21" data-loop="false">
                                    @foreach (var hinh in item.HinhAnhs)
                                    {
                                        if (hinh.BiXoa == false)
                                        {
                                            <li>
                                                <a href="SanPhams/HienThiChiTietSanPham/@hinh.MaSanPham">
                                                    <img src="@Url.Content("~/Images/" + hinh.TenHinh)" alt="@hinh.TenHinh" height="150" />
                                                </a>
                                            </li>
                                        }
                                    }
                                </ul>
                            </div>
                            <!-- product-imge-->
                        </div>
                        <div class="pb-right-column col-xs-12 col-sm-7">
                            @using (Html.BeginForm("Nhap", "GioHang", FormMethod.Get))
                            {
                                <h1 class="product-name">@item.TenSanPham</h1>

                                <div class="product-price-group">
                                    <span class="price">@item.GiaSanPham.GetValueOrDefault(0).ToString("N0") VNĐ</span>
                                </div>
                                    <div class="info-orther">                                       
                                        <p>Xuất Xứ: Chile</p>
                                    </div>
                                    <div class="product-desc">
                                        @item.MoTa
                                    </div>
                                    <div class="form-option">
                                        <p class="form-option-title">Tùy chọn:</p>

                                        <div class="attributes">
                                            <div class="attribute-label">Số lượng:</div>
                                            <div class="attribute-list product-qty">
                                                <div class="qty">
                                                    <input id="option-product-qty" type="text" value="1" name="Soluong" />
                                                    <input type="hidden" name="id" value="@item.MaSanPham" />
                                                </div>
                                            </div>
                                            <div class="attribute-label">Số lượng còn:</div>
                                            <div class="attribute-list product-qty">
                                                <div class="qty">
                                                    <input id="option-product-qty" type="text" value="@item.SoLuongTon" readonly />
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-action">
                                        <div class="button-group">

                                            <input type="submit" class="btn-add-cart" style="text-decoration: none;" value="Thêm vào giỏ hàng" />

                                        </div>
                                    </div>
                            }
                        </div>
                    </div>
                    <!-- tab product -->
                    <div class="product-tab">
                        <ul class="nav-tab">
                            <li class="active">
                                <a aria-expanded="false" data-toggle="tab" href="#product-detail" style="text-decoration: none;">Chi tiết sản phẩm</a>
                            </li>
                            <li>
                                <a aria-expanded="true" data-toggle="tab" href="#information" style="text-decoration: none;">Thông tin</a>
                            </li>
                        </ul>
                        <div class="tab-container">
                            <div id="product-detail" class="tab-panel active">@item.MoTa</div>
                            <div id="information" class="tab-panel">
                                <table class="table table-bordered">
                                    <tr>
                                        <td width="200">Xuất xứ: </td>
                                        <td>@item.HangSanXuat.TenHangSanXuat</td>
                                    </tr>
                                    <tr>
                                        <td>Loại: </td>
                                        <td>@item.LoaiSanPham.TenLoaiSanPham</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="fb-root"></div>
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9&appId=1770232879954779";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<center><div class="fb-comments" data-href="@Request.Url.AbsoluteUri" data-numposts="5"></div></center>
@{ Html.RenderAction("SanPhamCungLoai", "SanPhams");}

WineShop/Views/SanPhams/DanhSachSanPham.cshtml
@model PagedList.IPagedList<WineShop.Models.SanPham>
@using PagedList.Mvc;

@{ int n = Model.Count; }



<section class="section8 block-trending">
    <div class="section-container">
        <h2 class="section-title">@ViewBag.TieuDe</h2>
        <div class="section-content">
            <div class="container">
                <ul class="products-style8 row">

                        @foreach (var item in Model)
                        {

                            <li class="product col-sm-6 col-md-3">
                                <div class="product-container">
                                    <div class="product-thumb">
                                        <a href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">
                                            @foreach (var h in item.HinhAnhs)
                                            {
                                                <img src="~/Images/@h.TenHinh" width="180" height="320" />
                                                break;
                                            }
                                        </a>
                                        <span class="quick-view" >Xem chi tiết</span>
                                    </div>
                                    <div class="product-info">
                                        <div class="product-name">
                                            <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">@item.TenSanPham</a>
                                        </div>
                                        <div class="box-price">
                                            <span class="price">@item.GiaSanPham.GetValueOrDefault(0).ToString("N0") VND</span>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        }
                    </ul>
                <center>@Html.PagedListPager(Model, page => Url.Action(ViewBag.TenAction, new { page }))</center>
            </div>
        </div>
    </div>
</section>

WineShop/Views/SanPhams/MenuHang.cshtml
@model IEnumerable<WineShop.Models.HangSanXuat>

<div class="sub-menu">
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td width="400px">
                    @Html.ActionLink(item.TenHangSanXuat, "HienThiSanPhamTheoHang", "SanPhams", new { id = item.MaHangSanXuat }, null)

                </td>
            </tr>
        }
    </table>
</div>

WineShop/Views/SanPhams/MenuLoai.cshtml
@model IEnumerable<WineShop.Models.LoaiSanPham>

<div class="sub-menu">
    <table>
        @foreach (var item in Model)
        {
            <tr>
                <td width="400px">
                    @Html.ActionLink(item.TenLoaiSanPham, "HienThiSanPhamTheoLoai", "SanPhams", new { id = item.MaLoaiSanPham }, null)
                </td>
            </tr>
        }
    </table>
</div>

WineShop/Views/SanPhams/SanPhamCungLoai.cshtml
@model IEnumerable<WineShop.Models.SanPham>

<section class="section8 block-trending">
    <div class="section-container">
        <h2 class="section-title">@ViewBag.TieuDe</h2>
        <div class="section-content">
            <div class="container">
                <ul class="products-style8 row">
                    @foreach (var item in Model.ToList())
                    {

                        <li class="product col-sm-6 col-md-3">
                            <div class="product-container">
                                <div class="product-thumb">
                                    <a href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">
                                        @foreach (var h in item.HinhAnhs)
                                        {
                                            <img src="~/Images/@h.TenHinh" width="180" height="320" />
                                            break;
                                        }
                                    </a>
                                    <span class="quick-view" >Xem chi tiết</span>
                                </div>
                                <div class="product-info">
                                    <div class="product-name">
                                        <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">@item.TenSanPham</a>
                                    </div>
                                    <div class="box-price">
                                        <span class="price">@item.GiaSanPham.GetValueOrDefault(0).ToString("N0") VND</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</section>

WineShop/Views/SanPhams/Search.cshtml
@model IEnumerable<WineShop.Models.SanPham>

<div class="m-b-5 input-prepend inside search-form no-boarder">
    <div class="container main-header">
        <div id="nav">
            <div class="form-style-5">
                <table>
                    <tr>
                        <td>
                            @using (Html.BeginForm("TimKiemSP", "SanPhams"))
                            {
                                    <form>
                                        <fieldset>
                                            <input class="no-border" name="txtTimkiem" style="background-color: #e5e5e5; height: 33px; margin-right: 25px; border-radius:10px 0 0 10px;" placeholder="Nhập tên sản phẩm"/>

                                            @Html.DropDownList("MaLoaiSanPham", (IEnumerable<SelectListItem>)ViewBag.LSPs, "Chọn loại sản phẩm")

                                            @Html.DropDownList("MaHangSanXuat", (IEnumerable<SelectListItem>)ViewBag.HSXs, "Chọn nhà sản xuất")

                                            <input class="no-border" name="txtGia1" style="background-color: #e5e5e5; width: 100px; height: 33px; margin-right: 25px;  margin-left: 25px;" placeholder="Giá"/>

                                            <input class="no-border" name="txtGia2" style="background-color: #e5e5e5; width: 100px; height: 33px; margin-right: 25px;" placeholder="Giá"/>

                                            <button type="submit" style="background-color:#e5e5e5; height:33px; width: 30px; margin-right: 15px;"><img src="~/Images/icon-serach7.png" /></button>
                                        </fieldset>
                                    </form>
                            }
                        </td>

                        <td>

                            @using Microsoft.AspNet.Identity
                            @if (Request.IsAuthenticated)
                            {
                                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                {
                                    @Html.AntiForgeryToken()
                                <td>
                                    @Html.ActionLink(User.Identity.GetUserName(), "ChangePassword", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                                </td>
                                <td>
                                    <a href="javascript:document.getElementById('logoutForm').submit()">Đăng xuất</a>
                                </td>
                                }
                            }
                            else
                            {
                                <td>
                                    @Html.ActionLink("Đăng Nhập", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
                                </td>
                                <td>
                                    @Html.ActionLink("Đăng ký", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })
                                </td>
                            }
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>