WineShop/Controllers/ModulesController.cs
using WineShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WineShop.Controllers
{
    public class ModulesController : Controller
    {
        ShopRuouDBEntities db = new ShopRuouDBEntities();

        // GET: Modules


        [ChildActionOnly]
        public PartialViewResult TopHeader()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult HomeSlideder()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult TopBanner()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult TabProduct()
        {            
            ViewBag.TenTab1 = "Xem Nhiều";
            ViewBag.TenTab2 = "Bán Chạy Nhất";
            ViewBag.TenTab3 = "Mới Nhất";
            return PartialView("TabProduct");
        }

        [ChildActionOnly]
        public PartialViewResult XemNhieu()
        {
            List<SanPham> lstSanPham = db.SanPhams.Where(s => s.BiXoa == 0).OrderByDescending(s => s.SoLuocXem).Take(4).ToList<SanPham>();
            return PartialView("TabProductSP", lstSanPham);
        }

        [ChildActionOnly]
        public PartialViewResult BanChayNhat()
        {
            List<SanPham> lstSanPham = db.SanPhams.Where(s => s.BiXoa == 0).OrderByDescending(s => s.SoLuongBan).Take(4).ToList<SanPham>();
            return PartialView("TabProductSP", lstSanPham);
        }

        [ChildActionOnly]
        public PartialViewResult MoiNhat()
        {
            List<SanPham> lstSanPham = db.SanPhams.Where(s => s.BiXoa == 0).OrderByDescending(s => s.NgayNhap).Take(4).ToList<SanPham>();
            return PartialView("TabProductSP", lstSanPham);
        }

        [ChildActionOnly]
        public PartialViewResult BlockTrending()
        {
            List<SanPham> lstSanPham = db.SanPhams.Where(s => s.BiXoa == 0).OrderByDescending(s => s.SoLuongBan).Take(4).ToList<SanPham>();
            ViewBag.Ten = "Sản Phẩm Mua Nhiều Nhất";
            return PartialView("BlockTrending", lstSanPham);
        }

        [ChildActionOnly]
        public PartialViewResult BlockLogo()
        {
            List<SanPham> lstSanPham = db.SanPhams.Where(s => s.BiXoa == 0).ToList<SanPham>();
            return PartialView("BlockLogo", lstSanPham);
        }

        [ChildActionOnly]
        public PartialViewResult Footer()
        {
            return PartialView();
        }
    }
}

WineShop/Views/Modules/BlockLogo.cshtml
@model IEnumerable<WineShop.Models.SanPham>

<div class="block-manufacturer-logo">
    <div class="container">
        <ul class="products-style8 row owl-carousel" data-dots="false" data-loop="true" data-nav="true" data-margin="30" data-autoplayTimeout="1000" data-autoplayHoverPause="true" data-autoplay="true" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":4},"1000":{"items":6}}'>
            @foreach (var item in Model)
            {
                <li class="product col-sm-9 col-md-12">
                    <div class="product-container">
                        <div class="product-thumb">
                            <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">
                                @foreach (var h in item.HinhAnhs)
                                {
                                    <img src="~/Images/@h.TenHinh" width="50" height="200" alt="Sản phẩm" />
                                    break;
                                }
                            </a>
                        </div>
                        <div class="product-info">
                            <div class="product-name">
                                @item.TenSanPham
                            </div>

                        </div>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

WineShop/Views/Modules/BlockTrending.cshtml
@model IEnumerable<WineShop.Models.SanPham>

<section class="section8 block-trending">
    <div class="section-container">
        <h2 class="section-title">@ViewBag.Ten</h2>
        <div class="section-content">
            <div class="container">
                <ul class="products-style8 row">
                    @foreach (var item in Model)
                    {
                        <li class="product col-sm-6 col-md-3">
                            <div class="product-container">
                                <div class="product-thumb">
                                    <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">
                                        @foreach (var h in item.HinhAnhs)
                                        {
                                            <img src="~/Images/@h.TenHinh" width="200" height="350" />
                                            break;
                                        }
                                    </a>
                                    <span class="quick-view">Xem chi tiết</span>
                                </div>
                                <div class="product-info">
                                    <div class="product-name">
                                        <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">@item.TenSanPham</a>
                                    </div>
                                    <div class="box-price">
                                        <span class="price">@item.GiaSanPham.GetValueOrDefault(0).ToString("N0") vnđ</span>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</section>

WineShop/Views/Modules/Footer.cshtml
<footer id="footer2" class="footer-style8 parallax">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-3">
                    <div class="footer-logo">
                        <a href="/"><img src="~/assets/data/option4/Logo.png" alt="Logo"></a>
                    </div>
                </div>
                <div class="col-sm-8 col-md-6">
                    <div class="footer-menu">
                        <ul>
                            <li>@Html.ActionLink("Thông tin về chúng tôi", "HienThiThongTin", "Home")</li>
                            <li><a href="#" style="text-decoration: none;">Chi nhánh</a></li>
                            <li><a href="#" style="text-decoration: none;">Chính sách</a></li>
                            <li>@Html.ActionLink("Liên hệ", "HienThiLienHe", "Home")</li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4 col-md-3">
                    <div class="footer-social">
                        <ul>
                            <li><a class="facebook" href="https://www.facebook.com/groups/181289818973647/?ref=br_rs" style="text-decoration: none;"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="google-plus" href="https://mail.google.com/mail/u/2/#inbox" style="text-decoration: none;"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer paralax-->
    <div class="footer-paralax" style="background: url('~/assets/images/brand_prlx_bg-small.jpg') 50% 0 no-repeat fixed;">
        <div class="footer-row">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title" style="text-decoration: none;">Thông tin</h3>
                            <div class="widget-body">
                                <ul>
                                    <li>135B Trần Hưng Đạo, Q.1, TP.HCM</li>
                                    <li>0808-3508-8508</li>
                                    <li>vltteam14ck3@gmail.com</li>
                                    <li>Đường dây nóng: 088.888.888</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <h3 class="widget-title" style="text-decoration: none;">NHÀ TÀI TRỢ</h3>
                            <div class="widget-body">
                                <ul>
                                    <li>LiOA</li>
                                    <li>VietinBank</li>
                                    <li>Foody.vn</li>
                                    <li>ivivu.com</li>
                                    <li>Bliss</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="widget-container">
                            <div class="map">
                                <figure>
                                    <iframe width="600" height="250" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJhbMDwBUvdTERDfVwfFzOPhc&key=AIzaSyAyAqIkq-xIlT5H1C2mGPBW6ML_sGwqAUE" allowfullscreen></iframe>
                                </figure>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="footer-bottom-wapper">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="footer-coppyright">
                                Bản quyền © 2016 cửa hàng VLT. Tất cả các quyền được bảo vệ hợp pháp. Thiết kế bởi: VLTTEAM.
                            </div>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ./footer paralax-->
</footer>

WineShop/Views/Modules/HomeSlideder.cshtml
<div class="homeslide8">
    <ul class="bxslider-background home-slider8">
        <li class="item" style="background-image: url('../assets/data/option8/slider3.jpg');">
            <div class="content">
                <h3 class="title caption">Tuần lễ mua sắm tại Shop</h3>
                <h2 class="sub-title caption">Rượu làm nổi lên những điều thầm kín nhất.</h2>
                <p class="desc caption">
                    Một chút ái tình cũng như một chút rượu mạnh, cái gì quá cũng làm người ta mắc bệnh.<br />
                    Tình bạn nảy sinh qua chén trà, cốc rượu sẽ qua đi như hơi men, như giấc ngủ say.
                </p>
            </div>
        </li>
        <li class="item" style="background-image: url('../assets/data/option8/slider5.jpg');">
            <div class="content">
                <h3 class="title caption">Tuần lễ mua sắm tại Shop</h3>
                <h2 class="sub-title caption">Rượu làm nổi lên những điều thầm kín nhất.</h2>
                <p class="desc caption">
                    Một chút ái tình cũng như một chút rượu mạnh, cái gì quá cũng làm người ta mắc bệnh.<br />
                    Tình bạn nảy sinh qua chén trà, cốc rượu sẽ qua đi như hơi men, như giấc ngủ say.
                </p>
            </div>
        </li>
        <li class="item" style="background-image: url('../assets/data/option8/slider6.jpg');">
            <div class="content">
                <h3 class="title caption">Tuần lễ mua sắm tại Shop</h3>
                <h2 class="sub-title caption">Rượu làm nổi lên những điều thầm kín nhất.</h2>
                <p class="desc caption">
                    Một chút ái tình cũng như một chút rượu mạnh, cái gì quá cũng làm người ta mắc bệnh.<br />
                    Tình bạn nảy sinh qua chén trà, cốc rượu sẽ qua đi như hơi men, như giấc ngủ say.
                </p>
            </div>
        </li>
    </ul>
</div>

WineShop/Views/Modules/TabProduct.cshtml
<div class="block-tab-products">
    <div class="container">
        <ul class="nav-tab">
            <li class="active"><a style="text-decoration:none;" data-toggle="tab" href="#tab1">@ViewBag.TenTab1</a></li>
            <li><a style="text-decoration:none;" data-toggle="tab" href="#tab2">@ViewBag.TenTab2</a></li>
            <li><a style="text-decoration:none;" data-toggle="tab" href="#tab3">@ViewBag.TenTab3</a></li>
        </ul>
        <div class="tab-container">
            <div id="tab1" class="tab-panel active">
                @{Html.RenderAction("XemNhieu", "Modules");}
            </div>
            <div id="tab2" class="tab-panel">
                @{Html.RenderAction("BanChayNhat", "Modules");}
            </div>
            <div id="tab3" class="tab-panel">
                @{Html.RenderAction("MoiNhat", "Modules");}
            </div>
        </div>
    </div>
</div>

WineShop/Views/Modules/TabProductSP.cshtml
@model IEnumerable<WineShop.Models.SanPham>

<ul class="products-style8 row">
    @foreach (var item in Model)
    {
        <li class="product col-sm-6 col-md-3">
            <div class="product-container">
                <div class="product-thumb">
                    <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">
                        @foreach (var h in item.HinhAnhs)
                        {
                            <img src="~/Images/@h.TenHinh" width="200" height="380" />
                            break;
                        }
                    </a>
                    <span class="quick-view">Xem chi tiết</span>
                </div>
                <div class="product-info">
                    <div class="product-name">
                        <a style="text-decoration:none;" href="@Url.Action("HienThiChiTietSanPham","SanPhams", new { id = item.MaSanPham})">@item.TenSanPham</a>
                    </div>
                    <div class="box-price">
                        <span class="price">@item.GiaSanPham.GetValueOrDefault(0).ToString("N0") vnđ</span>
                    </div>
                </div>
            </div>
        </li>
    }
</ul>

WineShop/Views/Modules/TopHeader.cshtml
<div id="main-header">
    <div class="container main-header">
        <div class="row">
            <div class="col-xs-12 col-sm-3 col-lg-3 logo">
                <a href="@Url.Action("Index","Home")"><img alt="Kute Shop" src="~/assets/data/option4/Logo.png" /></a>
            </div>
            <div class="col-sm-10 col-md-7 col-lg-9 main-menu-wapper">
                <div id="main-menu" class="main-menu">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div id='cssmenu'>
                                <ul>
                                    <li>
                                        @Html.ActionLink("Trang chủ", "Index", "Home")
                                    </li>
                                    <li class='active has-sub'>
                                        <a href='#'><span>Loại Rượu</span></a>
                                        <ul>
                                            <li class='has-sub'>
                                                <a href="#">
                                                    @{ Html.RenderAction("MenuLoai", "SanPhams");}
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class='active has-sub'>
                                        <a href='#'><span>Hãng Rượu</span></a>
                                        <ul>
                                            <li class='has-sub'>
                                                <a href="#">
                                                    @{ Html.RenderAction("MenuHang", "SanPhams");}
                                                </a>
                                            </li>
                                        </ul>
                                    </li>

                                    <li class='active has-sub'>
                                        @Html.ActionLink("Thông tin", "HienThiThongTin", "Home")
                                    </li>
                                    <li class='active has-sub'>
                                        @Html.ActionLink("Liên hệ", "HienThiLienHe", "Home")
                                    </li>
                                    <li class="active has-sub">
                                        @if (Session["a"] != null && Session["a"].ToString() == "GioHang")
                                        {
                                        <li class="current">
                                            @if (Session["DangNhap"] != null)
                                            {
                                                <a href="@Url.Action("Index", "GioHang")">Giỏ hàng</a>
                                            }
                                        </li>
                                        }
                                        else
                                        {
                                            <li>
                                                @if (Session["DangNhap"] != null)
                                                {
                                                    <a href="@Url.Action("Index", "GioHang")">Giỏ hàng</a>
                                                }
                                            </li>
                                        }
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>